// <auto-generated />
using System;
using ESBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESBot.Infrastructure.Migrations
{
    [DbContext(typeof(EsBotDbContext))]
    [Migration("20260414102851_FixUserRelation")]
    partial class FixUserRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESBot.Domain.Entities.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SubmittedAnswerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAnswerId")
                        .IsUnique();

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizRequestId");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("QuizRequests");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.SubmittedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizItemId");

                    b.ToTable("SubmittedAnswers");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.EvaluationResult", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.SubmittedAnswer", "SubmittedAnswer")
                        .WithOne("EvaluationResult")
                        .HasForeignKey("ESBot.Domain.Entities.EvaluationResult", "SubmittedAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedAnswer");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.Message", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.UserSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizItem", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.QuizRequest", "QuizRequest")
                        .WithMany("Items")
                        .HasForeignKey("QuizRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizRequest");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizRequest", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.UserSession", "Session")
                        .WithMany("QuizRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.SubmittedAnswer", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.QuizItem", "QuizItem")
                        .WithMany("SubmittedAnswers")
                        .HasForeignKey("QuizItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizItem");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("ESBot.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizItem", b =>
                {
                    b.Navigation("SubmittedAnswers");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.QuizRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.SubmittedAnswer", b =>
                {
                    b.Navigation("EvaluationResult");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ESBot.Domain.Entities.UserSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("QuizRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
